parameters:
    file_validation:
        xml:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ text/xml ]
            mimeTypesErrorMessage: Please upload a valid XML file.

        csv:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ text/plain ]
            mimeTypesErrorMessage: Please upload a valid CSV file.

        image:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif ]
            mimeTypesErrorMessage: Please upload a valid PDF, GIF, JPG or PNG file.

        file:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif, text/x-pascal, text/plain, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, image/vnd.adobe.photoshop, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.openxmlformats-officedocument.presentationml.slideshow, application/vnd.openxmlformats-officedocument.presentationml.template, application/vnd.openxmlformats-officedocument.presentationml.slide, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.wordprocessingml.template, application/vnd.ms-excel.addin.macroEnabled.12, application/vnd.ms-excel.sheet.binary.macroEnabled.12, application/vnd.openxmlformats-officedocument.spreadsheetml.template, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/zip, application/x-rar-compressed ]
            mimeTypesErrorMessage: Please upload a valid file (plain text, PDF, JPG, GIF, PNG, CSV, DOC, DOCX, XLS, XLSX, PPT, PPTX).

services:
  odr.twig.plug_extension:
      class: ODR\AdminBundle\Twig\PlugExtension
      arguments: 
          container: "@service_container"
      tags:
          - { name: twig.extension }

  odr_search_controller:
      class: ODR\OpenRepository\SearchBundle\Controller\DefaultController
