# THIS APPEARS TO BE THE CURRENTLY USED VALIDATION FILE
# TODO Really need to add a function to further validate files including extension and content.
# Opening up to application/octet-stream allows valid binaries to be uploaded.
# Major security issue if directory structure is not protected.
parameters:
    file_validation:
        xml:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded xml file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ text/xml ]
            mimeTypesErrorMessage: Please upload a valid XML file.

        csv:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded csv file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ ]
            mimeTypesErrorMessage: Please upload a valid CSV file.

        image:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded image is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif ]
            mimeTypesErrorMessage: Please upload a valid PDF, GIF, JPG or PNG file.

        file:
            maxSize: 2048   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 2 GB.
            #mimeTypes: [ application/octet-stream, application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif, text/x-pascal, text/plain, text/csv, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, image/vnd.adobe.photoshop, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.openxmlformats-officedocument.presentationml.slideshow, application/vnd.openxmlformats-officedocument.presentationml.template, application/vnd.openxmlformats-officedocument.presentationml.slide, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.wordprocessingml.template, application/vnd.ms-excel.addin.macroEnabled.12, application/vnd.ms-excel.sheet.binary.macroEnabled.12, application/vnd.openxmlformats-officedocument.spreadsheetml.template, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/zip, application/x-rar-compressed ]
            #mimeTypesErrorMessage: Please upload a valid file (plain text, PDF, JPG, GIF, PNG, CSV, DOC, DOCX, XLS, XLSX, PPT, PPTX, TIFF, MS, CH).
            mimeTypes: [ ]
            mimeTypesErrorMessage: Please upload a valid file.

services:
    odr.twig.plug_extension:
        class: ODR\AdminBundle\Twig\PlugExtension
        arguments:
            container: "@service_container"
        tags:
            - { name: twig.extension }

    odr.markdown.parser:
        class: ODR\AdminBundle\Component\Service\ODRMarkdownParserService

    odr.custom_controller_service:
        class: ODR\OpenRepository\AdminBundle\Controller\ODRCustomController
        arguments: ['@doctrine.orm.entity_manager']

    odr_search_controller:
        class: ODR\OpenRepository\SearchBundle\Controller\DefaultController


    # Services for improved data retrieval model
    odr.cache_service:
        class: ODR\AdminBundle\Component\Service\CacheService
        arguments:
            cache_service: "@snc_redis.default"
            cache_prefix: "%memcached_key_prefix%"

    odr.crypto_service:
        class: ODR\AdminBundle\Component\Service\CryptoService
        arguments:
            cache_service: "@odr.cache_service"
            crypto_adapter: "@dterranova_crypto.crypto_adapter"
            crypto_dir: "%dterranova_crypto.temp_folder%"
            odr_web_dir: "%odr_web_directory%"
            entity_manager: "@doctrine.orm.entity_manager"
            logger: "@logger"

    odr.tab_helper_service:
        class: ODR\AdminBundle\Component\Service\ODRTabHelperService
        arguments:
            request_stack: "@request_stack"
            token_generator: "@fos_user.util.token_generator"

    odr.clone_datatype_service:
        class: ODR\AdminBundle\Component\Service\CloneDatatypeService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            clone_theme_service: "@odr.clone_theme_service"
            datatype_info_service: "@odr.datatype_info_service"
            permissions_service: "@odr.permissions_management_service"
            user_manager: "@fos_user.user_manager"
            logger: "@monolog.logger.clone_datatype"

    odr.clone_theme_service:
        class: ODR\AdminBundle\Component\Service\CloneThemeService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            theme_service: "@odr.theme_info_service"
            logger: "@monolog.logger.clone_theme"


    odr.permissions_management_service:
        class: ODR\AdminBundle\Component\Service\PermissionsManagementService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            datatype_info_service: "@odr.datatype_info_service"
            search_cache_service: "@odr.search_cache_service"
            user_manager: "@fos_user.user_manager"
            logger: "@logger"


    odr.datarecord_info_service:
        class: ODR\AdminBundle\Component\Service\DatarecordInfoService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            permissions_service: "@odr.permissions_management_service"
            datatype_info_service: "@odr.datatype_info_service"
            theme_service: "@odr.theme_info_service"
            templating: "@templating"
            token_manager: "@security.csrf.token_manager"
            token_storage: "@security.token_storage"
            logger: "@logger"

    odr.datatype_info_service:
        class: ODR\AdminBundle\Component\Service\DatatypeInfoService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            odr_web_dir: "%odr_web_directory%"
            logger: "@logger"

    odr.design_info_service:
        class: ODR\AdminBundle\Component\Service\DesignInfoService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            permissions_service: "@odr.permissions_management_service"
            datatype_info_service: "@odr.datatype_info_service"
            theme_service: "@odr.theme_info_service"
            templating: "@templating"
            token_manager: "@security.csrf.token_manager"
            token_storage: "@security.token_storage"
            logger: "@logger"

    odr.theme_info_service:
        class: ODR\AdminBundle\Component\Service\ThemeInfoService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            cache_service: "@odr.cache_service"
            datatype_info_service: "@odr.datatype_info_service"
            session: "@session"
            logger: "@logger"

    odr.table_theme_helper_service:
        class: ODR\AdminBundle\Component\Service\TableThemeHelperService
        arguments:
            container: "@service_container"    # needed in order to execute arbitrary render plugins
            cache_service: "@odr.cache_service"
            datarecord_info_service: "@odr.datarecord_info_service"
            datatype_info_service: "@odr.datatype_info_service"
            permissions_service: "@odr.permissions_management_service"
            theme_service: "@odr.theme_info_service"
            router: "@router"
            logger: "@logger"


    odr.datarecord_export_service:
        class: ODR\AdminBundle\Component\Service\DatarecordExportService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            datarecord_info_service: "@odr.datarecord_info_service"
            datatype_info_service: "@odr.datatype_info_service"
            permissions_service: "@odr.permissions_management_service"
            theme_service: "@odr.theme_info_service"
            templating: "@templating"
            logger: "@logger"

    odr.datatype_export_service:
        class: ODR\AdminBundle\Component\Service\DatatypeExportService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            datatype_info_service: "@odr.datatype_info_service"
            permissions_service: "@odr.permissions_management_service"
            theme_service: "@odr.theme_info_service"
            templating: "@templating"
            logger: "@logger"


    odr.tracked_job_service:
        class: ODR\AdminBundle\Component\Service\TrackedJobService
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"
            datatype_info_service: "@odr.datatype_info_service"
            logger: "@logger"


    # Defines a number of reusable classes to use inside Symfony forms
    odr.type.datafield_type:
        class: ODR\AdminBundle\Form\Type\DatafieldType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    odr.type.theme_element_type:
        class: ODR\AdminBundle\Form\Type\ThemeElementType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    odr.type.datatype_type:
        class: ODR\AdminBundle\Form\Type\DatatypeType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
