# THIS APPEARS TO BE THE CURRENTLY USED VALIDATION FILE
# TODO Really need to add a function to further validate files including extension and content.
# Opening up to application/octet-stream allows valid binaries to be uploaded.
# Major security issue if directory structure is not protected.
parameters:
    file_validation:
        xml:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded xml file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ text/xml ]
            mimeTypesErrorMessage: Please upload a valid XML file.

        csv:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded csv file is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ ]
            mimeTypesErrorMessage: Please upload a valid CSV file.

        image:
            maxSize: 100   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded image is too large.  Allowed maximum size is 100 MB.
            mimeTypes: [ application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif ]
            mimeTypesErrorMessage: Please upload a valid PDF, GIF, JPG or PNG file.

        file:
            maxSize: 2048   # maximum allowed filesize (in Mb) for this type of uploaded file
            maxSizeErrorMessage: The uploaded file is too large.  Allowed maximum size is 2 GB.
            #mimeTypes: [ application/octet-stream, application/pdf, application/x-pdf, image/jpeg, image/jpg, image/png, image/gif, text/x-pascal, text/plain, text/csv, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, image/vnd.adobe.photoshop, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.openxmlformats-officedocument.presentationml.slideshow, application/vnd.openxmlformats-officedocument.presentationml.template, application/vnd.openxmlformats-officedocument.presentationml.slide, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.wordprocessingml.template, application/vnd.ms-excel.addin.macroEnabled.12, application/vnd.ms-excel.sheet.binary.macroEnabled.12, application/vnd.openxmlformats-officedocument.spreadsheetml.template, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/zip, application/x-rar-compressed ]
            #mimeTypesErrorMessage: Please upload a valid file (plain text, PDF, JPG, GIF, PNG, CSV, DOC, DOCX, XLS, XLSX, PPT, PPTX, TIFF, MS, CH).
            mimeTypes: [ ]
            mimeTypesErrorMessage: Please upload a valid file.

services:
    odr.twig.plug_extension:
        class: ODR\AdminBundle\Twig\PlugExtension
        arguments:
            container: "@service_container"
        tags:
            - { name: twig.extension }

    odr_search_controller:
        class: ODR\OpenRepository\SearchBundle\Controller\DefaultController

    odr.crypto_service:
        class: ODR\AdminBundle\Component\Service\CryptoService
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
            logger: "@logger"

    odr.type.datafield_type:
        class: ODR\AdminBundle\Form\Type\DatafieldType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    odr.type.theme_element_type:
        class: ODR\AdminBundle\Form\Type\ThemeElementType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    odr.type.datatype_type:
        class: ODR\AdminBundle\Form\Type\DatatypeType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
