# ODR/AdminBundle/Resources/config/validation.yml

# Integer values can't be validated in here, because Symfony transforms them with a PHP (int) cast
#  prior to running any validation on the value.  ODR works around this by defining its own Integer
#  type that defines its own transformation.  @see ODR\AdminBundle\Form\Type\ODRIntegerType

# Decimal values also aren't validated in here...the forms use a regular TextType, and the Decimal
#  Entity does processing on the provided value to store both an "original" value for display, and
#  a floating point version for searching.

# http://symfony.com/doc/2.8/reference/constraints/Length.html
ODR\AdminBundle\Entity\ShortVarchar:
   properties:
        value:
            - Length:
                min: 0
                max: 32

ODR\AdminBundle\Entity\MediumVarchar:
   properties:
        value:
            - Length:
                min: 0
                max: 64

ODR\AdminBundle\Entity\LongVarchar:
   properties:
        value:
            - Length:
                min: 0
                max: 255


# TODO - http://symfony.com/doc/2.8/reference/constraints/Date.html ?
#ODR\AdminBundle\Entity\DatetimeValue:
#    properties:
#        birthday:
#            - Date: ~
