# FOSOAuthBundle - server side oauth login routes
odr_oauth_server_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: ODROpenRepositoryOAuthServerBundle:Security:oauthlogin }

odr_oauth_server_auth_login_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: ODROpenRepositoryOAuthServerBundle:Security:oauthloginCheck }
    requirements: { methods: POST }
