services:
    fos_oauth.preauth_event:
        class: ODR\OpenRepository\OAuthServerBundle\EventListener\OAuthEventListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    oauth.grant_extension.owned_client:
        class: ODR\OpenRepository\OAuthServerBundle\OAuth\OwnedClientGrantExtension
        tags:
            - { name: fos_oauth_server.grant_extension, uri: 'http://odr.io/grants/owned_client' }

    odr.oauth_server.client_manager:
        class: ODR\OpenRepository\OAuthServerBundle\OAuth\ClientManager
        arguments: [ "@doctrine.orm.entity_manager" ]
