imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing.yml" }
    profiler: { only_exceptions: true }

monolog:
    # Changes made to configuration here typically need to be made in config_dev.yml as well
    # https://symfony.com/doc/2.8/logging/channels_handlers.html
    channels: ['clone_datatype', 'clone_theme']

    handlers:
        # ideally stuff shouldn't write to this channel
        app:
            type:  stream
            path:  %kernel.logs_dir%/app.log
            level: debug
            channels: [app]

        # TODO - change debug level of these to info?
        clone_datatype:
            type:  stream
            path:  %kernel.logs_dir%/clone_datatype.log
            level: debug
            channels: [clone_datatype]
        clone_theme:
            type:  stream
            path:  %kernel.logs_dir%/clone_theme.log
            level: debug
            channels: [clone_theme]

        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
