jp_graph:
    resource: "@jpGraphBundle/Resources/config/routing.yml"
    prefix:   /

odr_open_repository_graph:
    resource: "@ODROpenRepositoryGraphBundle/Resources/config/routing.yml"
    prefix:   /

odr_open_repository_api:
    resource: "@ODROpenRepositoryApiBundle/Resources/config/routing.yml"
    prefix:   /

odr_open_repository_user:
    resource: "@ODROpenRepositoryUserBundle/Resources/config/routing.yml"
    prefix:   /

odr_admin:
    resource: "@ODRAdminBundle/Resources/config/routing.yml"
    prefix:   /

#odr_login:
#    resource: "@ODRLoginBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# MUST be last in this list due to use of a general catch-all route
odr_open_repository_search:
    resource: "@ODROpenRepositorySearchBundle/Resources/config/routing.yml"
    prefix:   /
