api_login_check:
    path: /api/v3/token
    methods: [POST]
    prefix: /odr

api_login_check_v4:
    path: /api/v4/token
    methods: [POST]
    prefix: /odr

# ----------------------------------------
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

# FOSUserBundle removed in the Symfony 5 upgrade; security + resetting routes are defined in
# @ODROpenRepositoryUser/Resources/config/routing.yml

# ----------------------------------------

# ----------------------------------------
# ODR routes
odr_open_repository_graph:
    resource: "@ODROpenRepositoryGraphBundle/Resources/config/routing.yml"
    prefix:   /odr/

odr_open_repository_api:
    resource: "@ODROpenRepositoryApiBundle/Resources/config/routing.yml"
    prefix:   /odr/

odr_open_repository_user:
    resource: "@ODROpenRepositoryUserBundle/Resources/config/routing.yml"
    prefix:   /odr/

odr_open_repository_jupyterhub_bridge:
    resource: "@ODROpenRepositoryJupyterhubBridgeBundle/Resources/config/routing.yml"
    prefix:   /odr/

odr_admin_rruff:
    resource: "@ODRAdminBundle/Resources/config/routing.yml"
    prefix:   /odr/

# ----------------------------------------
# ----------------------------------------
# MUST be last in this list due to use of a general catch-all route
odr_open_repository_search:
    resource: "@ODROpenRepositorySearchBundle/Resources/config/routing.yml"
    prefix:   /odr/
