services:
    fos_oauth.preauth_event:
        class: ODR\OpenRepository\OAuthBundle\EventListener\OAuthEventListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
