<?php 

/**
 * Open Data Repository Data Publisher
 * RRUFF References Plugin
 * (C) 2015 by Nathan Stone (nate.stone@opendatarepository.org)
 * (C) 2015 by Alex Pires (ajpires@email.arizona.edu)
 * Released under the GPLv2
 *
 * The RRUFF References plugin works like the standard references plugin, but also has an autogenerated
 * external ID.
 *
 */

namespace ODR\OpenRepository\GraphBundle\Plugins\RRUFF;

// Entities
use ODR\AdminBundle\Entity\DataFields;
// Events
use ODR\AdminBundle\Component\Event\DatafieldModifiedEvent;
use ODR\AdminBundle\Component\Event\DatarecordCreatedEvent;
// Exceptions
use ODR\AdminBundle\Exception\ODRBadRequestException;
use ODR\AdminBundle\Exception\ODRException;
// Services
use ODR\AdminBundle\Component\Service\CacheService;
use ODR\AdminBundle\Component\Service\EntityCreationService;
use ODR\AdminBundle\Component\Service\LockService;
use ODR\AdminBundle\Component\Service\SortService;
use ODR\OpenRepository\SearchBundle\Component\Service\SearchQueryService;
// ODR
use ODR\OpenRepository\GraphBundle\Plugins\DatatypePluginInterface;
use ODR\OpenRepository\GraphBundle\Plugins\SearchOverrideInterface;
// Symfony
use Doctrine\ORM\EntityManager;
use Symfony\Bridge\Monolog\Logger;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\Security\Csrf\CsrfTokenManager;


class RRUFFReferencesPlugin implements DatatypePluginInterface, SearchOverrideInterface
{

    /**
     * @var EntityManager
     */
    private $em;

    /**
     * @var CacheService
     */
    private $cache_service;

    /**
     * @var EntityCreationService
     */
    private $entity_create_service;

    /**
     * @var LockService
     */
    private $lock_service;

    /**
     * @var SearchQueryService
     */
    private $search_query_service;

    /**
     * @var SortService
     */
    private $sort_service;

    /**
     * @var EventDispatcherInterface
     */
    private $event_dispatcher;

    // NOTE - $dispatcher is an instance of \Symfony\Component\Event\EventDispatcher in prod mode,
    //  and an instance of \Symfony\Component\Event\Debug\TraceableEventDispatcher in dev mode

    /**
     * @var CsrfTokenManager
     */
    private $token_manager;

    /**
     * @var EngineInterface
     */
    private $templating;

    /**
     * @var Logger
     */
    private $logger;


    /**
     * RRUFF References constructor
     *
     * @param EntityManager $entity_manager
     * @param CacheService $cache_service
     * @param EntityCreationService $entity_create_service
     * @param LockService $lock_service
     * @param SearchQueryService $search_query_service
     * @param SortService $sort_service
     * @param EventDispatcherInterface $event_dispatcher
     * @param CsrfTokenManager $token_manager
     * @param EngineInterface $templating
     * @param Logger $logger
     */
    public function __construct(
        EntityManager $entity_manager,
        CacheService $cache_service,
        EntityCreationService $entity_create_service,
        LockService $lock_service,
        SearchQueryService $search_query_service,
        SortService $sort_service,
        EventDispatcherInterface $event_dispatcher,
        CsrfTokenManager $token_manager,
        EngineInterface $templating,
        Logger $logger
    ) {
        $this->em = $entity_manager;
        $this->cache_service = $cache_service;
        $this->entity_create_service = $entity_create_service;
        $this->lock_service = $lock_service;
        $this->search_query_service = $search_query_service;
        $this->sort_service = $sort_service;
        $this->event_dispatcher = $event_dispatcher;
        $this->token_manager = $token_manager;
        $this->templating = $templating;
        $this->logger = $logger;
    }


    /**
     * @inheritDoc
     */
    public function canExecutePlugin($render_plugin_instance, $datatype, $rendering_options)
    {
        if ( isset($rendering_options['context']) ) {
            $context = $rendering_options['context'];

            if ($context === 'display' || $context === 'edit'
                || $context === 'fake_edit' || $context === 'mass_edit'
            ) {
                // Needs to be executed in display, edit (for journal selection and previews),
                //  fake_edit (for autogeneration), and mass_edit (for switching to a specific journal)
                return true;
            }

            // Also need a "text" mode
            if ( $context === 'text' || $context === 'html' )
                return true;
        }

        // Otherwise, don't execute the plugin
        return false;
    }


    /**
     * @inheritDoc
     */
    public function execute($datarecords, $datatype, $render_plugin_instance, $theme_array, $rendering_options, $parent_datarecord = array(), $datatype_permissions = array(), $datafield_permissions = array(), $token_list = array())
    {
        try {
            // ----------------------------------------
            // If no rendering context set, then return nothing so ODR's default templating will
            //  do its job
            if ( !isset($rendering_options['context']) )
                return '';


            // ----------------------------------------
            // Need this to determine whether to throw an error or not
            $is_datatype_admin = $rendering_options['is_datatype_admin'];

            // Going to need these...
            $fields = $render_plugin_instance['renderPluginMap'];
            $options = $render_plugin_instance['renderPluginOptionsMap'];

            // The datatype array shouldn't be wrapped with its ID number here...
            $initial_datatype_id = $datatype['id'];

            // The theme array is stacked, so there should be only one entry to find here...
            $initial_theme_id = '';
            foreach ($theme_array as $t_id => $t)
                $initial_theme_id = $t_id;

            // There *should* only be a single datarecord in $datarecords...
            $datarecord = array();
            foreach ($datarecords as $dr_id => $dr)
                $datarecord = $dr;


            // ----------------------------------------
            // Output depends on which context the plugin is being executed from
            $context = $rendering_options['context'];
            $output = '';
            if ( $context === 'display' || $context === 'text' || $context === 'html' ) {

                // Want to locate the values for most of the mapped datafields
                $optional_fields = array(
                    'Reference ID' => 0
                );

                $datafield_mapping = array();
                foreach ($fields as $rpf_name => $rpf_df) {
                    // Need to find the real datafield entry in the primary datatype array
                    $rpf_df_id = $rpf_df['id'];

                    $df = null;
                    if ( isset($datatype['dataFields'][$rpf_df_id]) )
                        $df = $datatype['dataFields'][$rpf_df_id];

                    if ($df == null) {
                        // Optional fields don't have to exist for this plugin to work
                        if ( isset($optional_fields[$rpf_name]) )
                            continue;

                        // If the datafield doesn't exist in the datatype_array, then either the datafield
                        //  is non-public and the user doesn't have permissions to view it (most likely),
                        //  or the plugin somehow isn't configured correctly

                        // The plugin can't continue executing in either case...
                        if ( !$is_datatype_admin )
                            // ...regardless of what actually caused the issue, the plugin shouldn't execute
                            return '';
                        else
                            // ...but if a datatype admin is seeing this, then they probably should fix it
                            throw new \Exception('Unable to locate array entry for the field "'.$rpf_name.'", mapped to df_id '.$rpf_df_id.'...check plugin config.');
                    }
                    else {
                        // The non-optional fields really should all be public...so actually throw an
                        //  error if any of them aren't and the user can do something about it
                        if ( isset($optional_fields[$rpf_name]) )
                            continue;

                        // If the datafield is non-public...
                        $df_public_date = ($df['dataFieldMeta']['publicDate'])->format('Y-m-d H:i:s');
                        if ( $df_public_date == '2200-01-01 00:00:00' ) {
                            if ( !$is_datatype_admin )
                                // ...but the user can't do anything about it, then just refuse to execute
                                return '';
                            else
                                // ...the user can do something about it, so they need to fix it
                                throw new \Exception('The field "'.$rpf_name.'" is not public...all fields except reference_id MUST be public.');
                        }
                    }

                    $typeclass = $df['dataFieldMeta']['fieldType']['typeClass'];

                    // Grab the fieldname specified in the plugin's config file to use as an array key
                    $key = strtolower(str_replace(' ', '_', $rpf_name));

                    // The datafield may have a render plugin that should be executed, but only if
                    //  it's not a file field...
                    if ( !empty($df['renderPluginInstances']) && $typeclass !== 'File' ) {
                        foreach ($df['renderPluginInstances'] as $rpi_id => $rpi) {
                            if ( $rpi['renderPlugin']['render'] !== false ) {
                                // ...if it does, then create an array entry for it
                                $datafield_mapping[$key] = array(
                                    'datafield' => $df,
                                    'render_plugin_instance' => $rpi
                                );
                            }
                        }
                    }

                    // If it does have a render plugin, then don't bother looking in the datarecord array
                    //  for the value
                    if ( isset($datafield_mapping[$key]) )
                        continue;


                    // Otherwise, look for the value in the datarecord array
                    if ( !isset($datarecord['dataRecordFields'][$rpf_df_id]) ) {
                        // As far as the reference plugin is concerned, empty strings are acceptable
                        //  values when datarecordfield entries don't exist
                        $datafield_mapping[$key] = '';
                    }
                    else if ($typeclass === 'File') {
                        $datafield_mapping[$key] = array(
                            'datarecordfield' => $datarecord['dataRecordFields'][$rpf_df_id]
                        );
                    }
                    else {
                        // Don't need to execute a render plugin on this datafield's value...extract it
                        //  directly from the datarecord array
                        // $drf is guaranteed to exist at this point
                        $drf = $datarecord['dataRecordFields'][$rpf_df_id];
                        $value = '';

                        switch ($typeclass) {
                            case 'IntegerValue':
                                $value = $drf['integerValue'][0]['value'];
                                break;
                            case 'DecimalValue':
                                $value = $drf['decimalValue'][0]['value'];
                                break;
                            case 'ShortVarchar':
                                $value = $drf['shortVarchar'][0]['value'];
                                break;
                            case 'MediumVarchar':
                                $value = $drf['mediumVarchar'][0]['value'];
                                break;
                            case 'LongVarchar':
                                $value = $drf['longVarchar'][0]['value'];
                                break;
                            case 'LongText':
                                $value = $drf['longText'][0]['value'];
                                break;
                            case 'DateTimeValue':
                                $value = $drf['dateTimeValue'][0]['value']->format('Y-m-d');
                                if ($value == '9999-12-31')
                                    $value = '';
                                $datafield_mapping[$key] = $value;
                                break;

                            default:
                                throw new \Exception('Invalid Fieldtype');
                                break;
                        }

                        $datafield_mapping[$key] = trim($value);
                    }
                }

                // Need to try to ensure urls are valid...
                if ( $datafield_mapping['url'] !== '' ) {
                    // Ensure that DOIs that aren't entirely links still are valid
                    if ( strpos($datafield_mapping['url'], 'doi:') === 0 )
                        $datafield_mapping['url'] = 'https://doi.org/'.trim( substr($datafield_mapping['url'], 4) );

                    // Ensure that the values have an 'https://' prefix
                    if ( strpos($datafield_mapping['url'], 'http') !== 0 )
                        $datafield_mapping['url'] = 'https://'.$datafield_mapping['url'];
                }

                // Going to render the reference differently if it's top-level...
                $is_top_level = $rendering_options['is_top_level'];

                $output = $this->templating->render(
                    'ODROpenRepositoryGraphBundle:RRUFF:RRUFFReferences/rruffreferences_display.html.twig',
                    array(
                        'datarecord' => $datarecord,
                        'mapping' => $datafield_mapping,

                        'is_top_level' => $is_top_level,
                        'original_context' => $rendering_options['context'],
                    )
                );

                // If meant for text output, then replace all whitespace sequences with a single space
                if ( $rendering_options['context'] === 'text' )
                    $output = preg_replace('/(\s+)/', ' ', $output);
            }
            else if ( $context === 'fake_edit') {
                // Retrieve mapping between datafields and render plugin fields
                $autogenerate_df_id = null;
                $plugin_fields = array();
                foreach ($fields as $rpf_name => $rpf_df) {
                    // Need to find the real datafield entry in the primary datatype array
                    $rpf_df_id = $rpf_df['id'];

                    $df = null;
                    if ( isset($datatype['dataFields']) && isset($datatype['dataFields'][$rpf_df_id]) )
                        $df = $datatype['dataFields'][$rpf_df_id];

                    // Autogenerated fields will continue to work even if the user can't see them,
                    //  but probably should still complain about plugin mapping errors to datatype admins
                    if ($df == null && $is_datatype_admin)
                        throw new \Exception('Unable to locate array entry for the field "'.$rpf_name.'", mapped to df_id '.$rpf_df_id);

                    // Need to tweak display parameters for several of the fields...
                    $plugin_fields[$rpf_df_id] = $rpf_df;
                    $plugin_fields[$rpf_df_id]['rpf_name'] = $rpf_name;

                    // Need to generate a special token for the reference_id field
                    if ( $rpf_name === 'Reference ID' )
                        $autogenerate_df_id = $rpf_df_id;
                }

                // Need to provide a special token so the "Reference ID" field won't get ignored
                //  by FakeEdit due to preventing user edits...
                $token_id = 'FakeEdit_'.$datarecord['id'].'_'.$autogenerate_df_id.'_autogenerated';
                $token = $this->token_manager->getToken($token_id)->getValue();
                $special_tokens[$autogenerate_df_id] = $token;


                // Also want to provide a sorted list of the existing journals to the user to reduce
                //  input errors...
                $journal_df_id = 0;
                if ( !isset($fields['Journal']['id']) ) {
                    // If the Journal field doesn't exist, then the plugin can't continue executing
                    if ( !$is_datatype_admin )
                        // ...regardless of what actually caused the issue, the plugin shouldn't execute
                        return '';
                    else
                        // ...but if a datatype admin is seeing this, then they probably should fix it
                        throw new \Exception('Unable to locate array entry for the field "Journal"...check plugin config.');
                }

                $journal_df_id = $fields['Journal']['id'];
                $sort_data = $this->sort_service->sortDatarecordsByDatafield($journal_df_id);

                $journal_list = array();
                foreach ($sort_data as $dr_id => $sort_value)
                    $journal_list[$sort_value] = 1;


                $output = $this->templating->render(
                    'ODROpenRepositoryGraphBundle:RRUFF:RRUFFReferences/rruffreferences_fakeedit_fieldarea.html.twig',
                    array(
                        'datatype_array' => array($initial_datatype_id => $datatype),
                        'datarecord_array' => array($datarecord['id'] => $datarecord),
                        'theme_array' => $theme_array,

                        'target_datatype_id' => $initial_datatype_id,
                        'parent_datarecord' => $parent_datarecord,
                        'target_datarecord_id' => $datarecord['id'],
                        'target_theme_id' => $initial_theme_id,

                        'datatype_permissions' => $datatype_permissions,
                        'datafield_permissions' => $datafield_permissions,

                        'is_top_level' => $rendering_options['is_top_level'],
                        'is_link' => $rendering_options['is_link'],
                        'display_type' => $rendering_options['display_type'],

                        'token_list' => $token_list,
                        'special_tokens' => $special_tokens,

                        'plugin_fields' => $plugin_fields,

                        'journal_df_id' => $journal_df_id,
                        'journal_list' => $journal_list,
                    )
                );
            }
            else if ( $context === 'edit' || $context === 'mass_edit' ) {
                // Want to provide a sorted list of the existing journals to the user to reduce
                //  input errors...
                $journal_df_id = 0;
                if ( !isset($fields['Journal']['id']) ) {
                    // If the Journal field doesn't exist, then the plugin can't continue executing
                    if ( !$is_datatype_admin )
                        // ...regardless of what actually caused the issue, the plugin shouldn't execute
                        return '';
                    else
                        // ...but if a datatype admin is seeing this, then they probably should fix it
                        throw new \Exception('Unable to locate array entry for the field "Journal"...check plugin config.');
                }

                $journal_df_id = $fields['Journal']['id'];
                $sort_data = $this->sort_service->sortDatarecordsByDatafield($journal_df_id);

                $journal_list = array();
                foreach ($sort_data as $dr_id => $sort_value)
                    $journal_list[$sort_value] = 1;

                if ( $context === 'edit' ) {
                    // Most of the fields need slightly modified saving javascript...
                    $reference_field_list = array();
                    foreach ($fields as $rpf_name => $rpf) {
                        switch ($rpf_name) {
                            case 'Authors':
                            case 'Article Title':
                            case 'Journal':
                            case 'Year':
                            case 'Month':
                            case 'Volume':
                            case 'Issue':
                            case 'Book Title':
                            case 'Publisher':
                            case 'Publisher Location':
                            case 'Pages':
                            case 'File':
                            case 'URL':
                                $reference_field_list[ $rpf['id'] ] = $rpf_name;
                                break;
                        }
                    }

                    // Also need a list of which datafields are using the chemistry plugin
                    // TODO - figure out some way to make plugins play nicer with each other?
                    $chemistry_plugin_fields = array();
                    foreach ($datatype['dataFields'] as $df_id => $df) {
                        foreach ($df['renderPluginInstances'] as $rpi_id => $rpi) {
                            if ( $rpi['renderPlugin']['pluginClassName'] === 'odr_plugins.base.chemistry' ) {
                                $subscript_delimiter = $rpi['renderPluginOptionsMap']['subscript_delimiter'];
                                $superscript_delimiter = $rpi['renderPluginOptionsMap']['superscript_delimiter'];

                                $chemistry_plugin_fields[$df_id] = array(
                                    'subscript_delimiter' => $subscript_delimiter,
                                    'superscript_delimiter' => $superscript_delimiter,
                                );
                            }
                        }
                    }

                    // Need to be able to pass this option along if doing edit mode
                    $edit_shows_all_fields = $rendering_options['edit_shows_all_fields'];
                    $edit_behavior = $rendering_options['edit_behavior'];

                    $output = $this->templating->render(
                        'ODROpenRepositoryGraphBundle:RRUFF:RRUFFReferences/rruffreferences_edit_fieldarea.html.twig',
                        array(
                            'datatype_array' => array($initial_datatype_id => $datatype),
                            'datarecord_array' => array($datarecord['id'] => $datarecord),
                            'theme_array' => $theme_array,

                            'target_datatype_id' => $initial_datatype_id,
                            'parent_datarecord' => $parent_datarecord,
                            'target_datarecord_id' => $datarecord['id'],
                            'target_theme_id' => $initial_theme_id,

                            'datatype_permissions' => $datatype_permissions,
                            'datafield_permissions' => $datafield_permissions,
                            'edit_shows_all_fields' => $edit_shows_all_fields,
                            'edit_behavior' => $edit_behavior,

                            'is_top_level' => $rendering_options['is_top_level'],
                            'is_link' => $rendering_options['is_link'],
                            'display_type' => $rendering_options['display_type'],

                            'token_list' => $token_list,

                            'reference_field_list' => $reference_field_list,
                            'chemistry_plugin_fields' => $chemistry_plugin_fields,
                            'journal_list' => $journal_list,
                        )
                    );
                }
                else if ( $context === 'mass_edit' ) {
                    $output = $this->templating->render(
                        'ODROpenRepositoryGraphBundle:RRUFF:RRUFFReferences/rruffreferences_massedit_fieldarea.html.twig',
                        array(
                            'datatype_array' => array($initial_datatype_id => $datatype),
                            'theme_array' => $theme_array,

                            'target_datatype_id' => $initial_datatype_id,
                            'target_theme_id' => $initial_theme_id,

                            'is_datatype_admin' => $is_datatype_admin,
                            'datatype_permissions' => $datatype_permissions,
                            'datafield_permissions' => $datafield_permissions,

                            'is_top_level' => $rendering_options['is_top_level'],

                            'mass_edit_trigger_datafields' => $rendering_options['mass_edit_trigger_datafields'],

                            'journal_df_id' => $journal_df_id,
                            'journal_list' => $journal_list,
                        )
                    );
                }
            }

            return $output;
        }
        catch (\Exception $e) {
            // Just rethrow the exception
            throw $e;
        }
    }


    /**
     * @inheritDoc
     */
    public function canExecuteSearchPlugin($render_plugin_instance, $datatype, $datafield, $rendering_options)
    {
        // Only want to override the Journal field
        if ( isset($render_plugin_instance['renderPluginMap']['Journal']['id']) ) {
            $journal_df_id = $render_plugin_instance['renderPluginMap']['Journal']['id'];
            return array('Journal' => $journal_df_id);
        }

        // If the journal field isn't mapped for some reason, return nothing
        return array();
    }


    /**
     * @inheritDoc
     */
    public function executeSearchPlugin($render_plugin_instance, $datatype, $datafield, $preset_value, $rendering_options)
    {
        // This will only be called on the Journal field...want to provide a dropdown of all journals
        //  currently listed in the field
        $sort_data = $this->sort_service->sortDatarecordsByDatafield( $datafield['id'] );

        $journal_list = array();
        foreach ($sort_data as $dr_id => $sort_value)
            $journal_list[$sort_value] = 1;

        $output = $this->templating->render(
            'ODROpenRepositoryGraphBundle:RRUFF:RRUFFReferences/rruffreferences_search_journal_datafield.html.twig',
            array(
                'datatype' => $datatype,
                'datafield' => $datafield,

                'journal_list' => $journal_list,

                'preset_value' => $preset_value,
            )
        );

        return $output;
    }


    /**
     * @inheritDoc
     */
    public function getSearchOverrideFields($df_list)
    {
        // The array entry for 'Journal' will only exist if the search system needs to run a search
        //  on the field
        if ( isset($df_list['Journal']) )
            return array( 'Journal' => $df_list['Journal'] );
        else
            return array();
    }


    /**
     * @inheritDoc
     */
    public function searchOverriddenField($datafield, $search_term, $render_plugin_fields, $render_plugin_options)
    {
        // The goal is to modify the Journal field so doublequotes around the search term are treated
        //  as matching the entire field, instead of just a ~phrase~ inside the field...which is how
        //  SearchQueryService::parseField() behaves by default
        // e.g.  "\"Inorganic Chemistry\"" should not match "\"Inorganic Chemistry Communications\""

        // ----------------------------------------
        // Have to re-implement SearchService::searchTextOrNumberDatafield() here, so that the call
        //  to SearchQueryService::searchTextOrNumberDatafield() can receive a different parameter
        $allowed_typeclasses = array(
            'LongText'
        );
        $typeclass = $datafield->getFieldType()->getTypeClass();
        if ( !in_array($typeclass, $allowed_typeclasses) )
            throw new ODRBadRequestException('RRUFFReferencesPlugin::searchOverriddenField() called with '.$typeclass.' datafield', 0xbf8b897d);


        // ----------------------------------------
        // See if this search result is already cached...
        $cached_searches = $this->cache_service->get('cached_search_df_'.$datafield->getId());
        if ( !$cached_searches )
            $cached_searches = array();

        // Since MYSQL's collation is case-insensitive, the php caching should treat it the same
        $value = $search_term['value'];
        $cache_key = mb_strtolower($value);
        if ( isset($cached_searches[$cache_key]) )
            return $cached_searches[$cache_key];


        // ----------------------------------------
        // Otherwise, going to need to run the search again...

        // The entire reason why searches of this field get overridden is so that doublequotes
        //  match the entire field instead of just a substring
        // e.g. "\"Inorganic Chemistry\"" should not match "\"Inorganic Chemistry Communications\""
        $doublequotes_force_exact_match = true;

        $result = $this->search_query_service->searchTextOrNumberDatafield(
            $datafield->getDataType()->getId(),
            $datafield->getId(),
            $typeclass,
            $value,
            $doublequotes_force_exact_match
        );

        $end_result = array(
            'dt_id' => $datafield->getDataType()->getId(),
            'records' => $result['records'],
            'guard' => $result['guard'],
        );

        // ...then recache the search result
        $cached_searches[$cache_key] = $end_result;
        $this->cache_service->set('cached_search_df_'.$datafield->getId(), $cached_searches);

        // ...then return it
        return $end_result;
    }


    /**
     * Handles when a datarecord is created.
     *
     * @param DatarecordCreatedEvent $event
     */
    public function onDatarecordCreate(DatarecordCreatedEvent $event)
    {
        // Pull some required data from the event
        $user = $event->getUser();
        $datarecord = $event->getDatarecord();
        $datatype = $datarecord->getDataType();

        // Need to locate the "reference_id" field for this render plugin...
        $query = $this->em->createQuery(
           'SELECT df
            FROM ODRAdminBundle:RenderPlugin rp
            JOIN ODRAdminBundle:RenderPluginInstance rpi WITH rpi.renderPlugin = rp
            JOIN ODRAdminBundle:RenderPluginMap rpm WITH rpm.renderPluginInstance = rpi
            JOIN ODRAdminBundle:DataFields df WITH rpm.dataField = df
            JOIN ODRAdminBundle:RenderPluginFields rpf WITH rpm.renderPluginFields = rpf
            WHERE rp.pluginClassName = :plugin_classname AND rpi.dataType = :datatype
            AND rpf.fieldName = :field_name
            AND rp.deletedAt IS NULL AND rpi.deletedAt IS NULL AND rpm.deletedAt IS NULL
            AND df.deletedAt IS NULL'
        )->setParameters(
            array(
                'plugin_classname' => 'odr_plugins.rruff.rruff_references',
                'datatype' => $datatype->getId(),
                'field_name' => 'Reference ID'
            )
        );
        $results = $query->getResult();
        if ( count($results) !== 1 )
            throw new ODRException('Unable to find the "Reference ID" field for the "RRUFF References" RenderPlugin, attached to Datatype '.$datatype->getId());

        // Will only be one result, at this point
        $datafield = $results[0];
        /** @var DataFields $datafield */


        // ----------------------------------------
        // Need to acquire a lock to ensure that there are no duplicate values
        $lockHandler = $this->lock_service->createLock('datatype_'.$datatype->getId().'_autogenerate_id'.'.lock', 15);    // 15 second ttl
        if ( !$lockHandler->acquire() ) {
            // Another process is in the mix...block until it finishes
            $lockHandler->acquire(true);
        }

        // Now that a lock is acquired, need to find the "most recent" value for the field that is
        //  getting incremented...
        $old_value = self::findCurrentValue($datafield->getId());

        // Since the "most recent" mineral id is already an integer, just add 1 to it
        $new_value = $old_value + 1;

        // Create a new storage entity with the new value
        $this->entity_create_service->createStorageEntity($user, $datarecord, $datafield, $new_value, false);    // guaranteed to not need a PostUpdate event
        $this->logger->debug('Setting df '.$datafield->getId().' "Reference ID" of new dr '.$datarecord->getId().' to "'.$new_value.'"...', array(self::class, 'onDatarecordCreate()'));

        // No longer need the lock
        $lockHandler->release();


        // ----------------------------------------
        // Fire off an event notifying that the modification of the datafield is done
        try {
            $event = new DatafieldModifiedEvent($datafield, $user);
            $this->event_dispatcher->dispatch(DatafieldModifiedEvent::NAME, $event);
        }
        catch (\Exception $e) {
            // ...don't want to rethrow the error since it'll interrupt everything after this
            //  event
//            if ( $this->container->getParameter('kernel.environment') === 'dev' )
//                throw $e;
        }

        // ...don't need to mark the datarecord as updated though
    }


    /**
     * For this database, the reference_id needs to be autogenerated.
     *
     * Don't particularly like random render plugins finding random stuff from the database, but
     * there's no other way to satisfy the design requirements.
     *
     * @param int $datafield_id
     *
     * @return int
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    private function findCurrentValue($datafield_id)
    {
        // Going to use native SQL...DQL can't use limit without using querybuilder...
        // NOTE - the query intentionally includes deleted entries, since we never want to reuse
        //  reference_ids even if the associated mineral got deleted for some reason
        $query =
           'SELECT e.value
            FROM odr_integer_value e
            WHERE e.data_field_id = :datafield
            ORDER BY e.value DESC
            LIMIT 0,1';
        $params = array(
            'datafield' => $datafield_id,
        );
        $conn = $this->em->getConnection();
        $results = $conn->executeQuery($query, $params);

        // Should only be one value in the result...
        $current_value = null;
        foreach ($results as $result)
            $current_value = intval( $result['value'] );

        // ...but if there's not for some reason, return zero as the "current".  onDatarecordCreate()
        //  will increment it so that the value one is what will actually get saved.
        // NOTE - this shouldn't happen for the existing references
        if ( is_null($current_value) )
            $current_value = 0;

        return $current_value;
    }
}
