#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
umask(0000);

set_time_limit(0);

// Tell AppKernel which app/ directory this invocation is for. When this
// console script is itself a symlink (linked-instance setup), __DIR__ and
// realpath()-style lookups resolve to the source tree, so AppKernel ends up
// loading config from the wrong instance. argv[0] is the path the user
// typed and is NOT symlink-resolved, so dirname(argv[0]) is the linked
// instance's app/ directory.
if (!defined('ODR_APP_DIR')) {
    $odr_console_path = $_SERVER['argv'][0];
    if (substr($odr_console_path, 0, 1) !== '/')
        $odr_console_path = getcwd() . '/' . $odr_console_path;
    define('ODR_APP_DIR', dirname($odr_console_path));
}

/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require __DIR__.'/../app/autoload.php';
require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);


use ODR\AdminBundle\Command\RefreshCommand;
$app_tmp = new Application();
$app_tmp->add(new RefreshCommand);
$app_tmp->run();

/*
use Symfony\Component\Process\Process;
$process = new Process('php app/console test:refresh');
$process->run();

// executes after the command finishes
if (!$process->isSuccessful()) {
    throw new \RuntimeException($process->getErrorOutput());
}

print $process->getOutput(); 
*/

/*
$fp = tmpFile();
$input = new StringInput('test:refresh');
$output = new StreamOutput($fp);
$app_tmp->run($input, $output);
*/
