parameters:
#    odr_open_repository_graph.example.class: ODR\OpenRepository\GraphBundle\Example

services:
    graph.graphplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\GraphPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
            logger: "@logger"
    graph.diffractionplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\DiffractionPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
    graph.referencesplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\ReferencesPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
    graph.commentplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CommentPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
            session: "@session"
    graph.chemistryplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\ChemistryPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
    graph.urlplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\URLPlugin
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"

    graph.defaultplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\DefaultPlugin
