parameters:
#    odr_open_repository_graph.example.class: ODR\OpenRepository\GraphBundle\Example

services:
    graph.chemined1plugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminED1Plugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.cheminedaplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEDAPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.cheminedsplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEDSPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.cheminee1plugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEE1Plugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.chemineeaplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEEAPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.chemineesplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEESPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.cheminefmplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminEFMPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.cheminetrplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CheminETRPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"

    graph.csvtableplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CSVTablePlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
    graph.graphplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\GraphPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
            container: "@service_container"
    graph.gcmsplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\GCMassSpecPlugin
        arguments:
            templating: "@templating"
            logger: "@logger"
    graph.referencesplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\ReferencesPlugin
        arguments:
            templating: "@templating"
    graph.commentplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\CommentPlugin
        arguments:
            templating: "@templating"
    graph.linkplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\LinkPlugin
        arguments:
            templating: "@templating"

    graph.chemistryplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\ChemistryPlugin
        arguments:
            templating: "@templating"
    graph.urlplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\URLPlugin
        arguments:
            templating: "@templating"

    graph.organizationplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\OrganizationPlugin
        arguments:
            templating: "@templating"
    graph.personplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\PersonPlugin
        arguments:
            templating: "@templating"
    graph.sampleplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\SamplePlugin
        arguments:
            templating: "@templating"
    graph.siteplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\SitePlugin
        arguments:
            templating: "@templating"

    graph.defaultplugin:
        class: ODR\OpenRepository\GraphBundle\Plugins\DefaultPlugin
        arguments:
            templating: "@templating"
