DataTree:
    type: entity
    table: odr_data_tree
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        ancestor:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ancestor_id:
                    referencedColumnName: id
            orphanRemoval: false
        descendant:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                descendant_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
