FieldType:
    type: entity
    table: odr_field_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        typeName:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: type_name
        description:
            type: text
            nullable: true
        isImage:
            type: boolean
            nullable: false
            column: is_image
        hasBlob:
            type: boolean
            nullable: false
            column: has_blob
    lifecycleCallbacks: {  }
