File:
    type: entity
    table: odr_file
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fileData:
            type: blob
            nullable: false
            column: file_data
        caption:
            type: string
            length: 96
            fixed: false
            nullable: true
        originalFileName:
            type: string
            length: 128
            fixed: false
            nullable: false
            column: original_file_name
        localFileName:
            type: string
            length: 128
            fixed: false
            nullable: false
            column: local_file_name
    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false
        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        dataRecord:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_record_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
