ImageSizes:
    type: entity
    table: odr_image_sizes
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        width:
            type: integer
            unsigned: false
            nullable: false
        height:
            type: integer
            unsigned: false
            nullable: false
        minWidth:
            type: integer
            unsigned: false
            nullable: true
            column: min_width
        minHeight:
            type: integer
            unsigned: false
            nullable: true
            column: min_height
        maxWidth:
            type: integer
            unsigned: false
            nullable: true
            column: max_width
        maxHeight:
            type: integer
            unsigned: false
            nullable: true
            column: max_height
    manyToOne:
        fieldType:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
