Theme:
    type: entity
    table: odr_theme
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        templateName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: template_name
        templateDescription:
            type: text
            nullable: true
            column: template_description
        templatePreview:
            type: blob
            nullable: true
            column: template_preview
        isDefault:
            type: boolean
            nullable: false
            column: is_default
    lifecycleCallbacks: {  }
