# These blacklisted strings should all be lowercase
# TODO - add other ones commonly used by bots looking for easy pickings...
parameters:
    odr.search_slug_blacklist: "admin|api|app|beanstalk|bin|csvimport|csvexport|dashboard|design|docs|edit|jobs|login|login-check|logout|massedit|oauth|profile|profile_edit|profile_save|redirect|resetting|save_fragment|search|session|src|user|vendor|view|web"

services:
    odr_custom_controller:
        class: ODR\AdminBundle\Controller\ODRCustomController

    odr.search_api_service_no_conflict:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchAPIServiceNoConflict
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $datatree_info_service: "@odr.datatree_info_service"
            $datarecord_export_service: "@odr.datarecord_export_service"
            $search_service: "@odr.search_service"
            $search_cache_service: "@odr.search_cache_service"
            $search_key_service: "@odr.search_key_service"
            $sort_service: "@odr.sort_service"
            $cache_service: "@odr.cache_service"
            $logger: "@logger"

    odr.search_sidebar_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchSidebarService
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $datatype_info_service: "@odr.datatype_info_service"
            $permissions_service: "@odr.permissions_management_service"
            $user_manager: "@fos_user.user_manager"
            $logger: "@logger"

    odr.search_api_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchAPIService
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $datatree_info_service: "@odr.datatree_info_service"
            $search_service: "@odr.search_service"
            $search_cache_service: "@odr.search_cache_service"
            $search_key_service: "@odr.search_key_service"
            $sort_service: "@odr.sort_service"
            $cache_service: "@odr.cache_service"
            $logger: "@logger"

    odr.search_cache_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchCacheService
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $cache_service: "@odr.cache_service"
            $search_service: "@odr.search_service"
            $logger: "@logger"

    odr.search_key_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchKeyService
        arguments:
            $datatype_info_service: "@odr.datatype_info_service"
            $search_service: "@odr.search_service"
            $user_manager: "@fos_user.user_manager"
            $logger: "@logger"

    odr.search_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchService
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $cache_service: "@odr.cache_service"
            $datatree_info_service: "@odr.datatree_info_service"
            $tag_helper_service: "@odr.tag_helper_service"
            $search_query_service: "@odr.search_query_service"
            $logger: "@logger"


    odr.search_query_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchQueryService
        public: false
        arguments:
            $entity_manager: "@doctrine.orm.entity_manager"
            $logger: "@logger"


    odr.search_redirect_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchRedirectService
        arguments:
            $tab_helper_service: "@odr.tab_helper_service"
            $router: "@router"
            $templating: "@templating"
            $logger: "@logger"

