parameters:
#    odr_open_repository_search.example.class: ODR\OpenRepository\SearchBundle\Example

services:
#    odr_open_repository_search.example:
#        class: %odr_open_repository_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    odr_custom_controller:
        class: ODR\AdminBundle\Controller\ODRCustomController

    odr.permissions_management_service:
        class: ODR\AdminBundle\Component\Service\PermissionsManagementService
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
            logger: "@logger"

    odr.datarecord_info_service:
        class: ODR\AdminBundle\Component\Service\DatarecordInfoService
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
            logger: "@logger"

    odr.datatype_info_service:
        class: ODR\AdminBundle\Component\Service\DatatypeInfoService
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
            logger: "@logger"

