# These blacklisted strings should all be lowercase
# TODO - add other ones commonly used by bots looking for easy pickings...
parameters:
    odr.search_slug_blacklist: "admin|api|app|beanstalk|bin|design|docs|edit|jobs|login|login-check|logout|oauth|profile|redirect|resetting|save_fragment|search|src|vendor|view|web"

services:
    odr_custom_controller:
        class: ODR\AdminBundle\Controller\ODRCustomController


    odr.search_cache_service:
        class: ODR\OpenRepository\SearchBundle\Component\Service\SearchCacheService
        arguments:
            odr_cache_service: "@odr.cache_service"
            logger: "@logger"
