ODR\AdminBundle\Entity\DataRecord:
    type: entity
    table: odr_data_record
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        provisioned:
            type: boolean
            nullable: false
            default: true

        unique_id:
            type: string
            length: 32
            nullable: true
            default: ''
            column: unique_id

#        external_id:
#            type: string
#            length: 255
#            fixed: false
#            nullable: false
#            default: ''
#            column: external_id
#            gedmo:
#                - versioned
#        namefield_value:
#            type: string
#            length: 255
#            fixed: false
#            nullable: false
#            default: ''
#            column: namefield_value
#            gedmo:
#                - versioned
#        sortfield_value:
#            type: string
#            length: 255
#            fixed: false
#            nullable: false
#            default: ''
#            column: sortfield_value
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: EXTRA_LAZY
            orphanRemoval: false

        grandchildren:
            targetEntity: DataRecord
            mappedBy: grandparent
            fetch: EXTRA_LAZY
        children:
            targetEntity: DataRecord
            mappedBy: parent
            fetch: EXTRA_LAZY

        dataRecordMeta:
            targetEntity: DataRecordMeta
            cascade: { }
            mappedBy: dataRecord
            inversedBy: null
            orphanRemoval: false

        linkedDatarecords:
            targetEntity: LinkedDataTree
            cascade: { }
            mappedBy: ancestor
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        parent:
            targetEntity: DataRecord
            inversedBy: children
            fetch: EXTRA_LAZY

        grandparent:
            targetEntity: DataRecord
            fetch: EXTRA_LAZY
            inversedBy: grandchildren

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
