ODR\AdminBundle\Entity\DataTreeMeta:
    type: entity
    table: odr_data_tree_meta
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        is_link:
            type: boolean
            nullable: false
            default: false
            column: is_link
#            gedmo:
#                - versioned
        multiple_allowed:
            type: boolean
            nullable: false
            default: true
            column: multiple_allowed
#            gedmo:
#                - versioned

        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        dataTree:
            targetEntity: DataTree
            cascade: {  }
            mappedBy: null
            inversedBy: dataTreeMeta
            joinColumns:
                data_tree_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }
