ODR\AdminBundle\Entity\DataTypeMeta:
    type: entity
    table: odr_data_type_meta
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        searchSlug:
            type: string
            length: 32
            fixed: false
            nullable: true
            column: search_slug
#            gedmo:
#                - versioned
        shortName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: short_name
#            gedmo:
#                - versioned
        longName:
            type: string
            length: 128
            fixed: false
            nullable: false
            column: long_name
#            gedmo:
#                - versioned
        description:
            type: text
            fixed: false
            nullable: true
            column: description
#            gedmo:
#                - versioned
        xml_shortName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: xml_short_name
#            gedmo:
#                - versioned

        useShortResults:
            type: boolean
            nullable: false
            default: true
            column: use_short_results
#            gedmo:
#                - versioned

        display_type:
            type: integer
            nullable: false
            default: 0
            column: display_type
#            gedmo:
#                - versioned

        publicDate: 
            type: datetime
            nullable: false
            column: public_date
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    manyToOne:
        externalIdField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
#                data_fields_id:
                external_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
#            fetch: EXTRA_LAZY
#            gedmo:
#                - versioned
        nameField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_name_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
#            fetch: EXTRA_LAZY
#            gedmo:
#                - versioned
        sortField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sort_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
#            fetch: EXTRA_LAZY
#            gedmo:
#                - versioned
        backgroundImageField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                background_image_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
#            fetch: EXTRA_LAZY
#            gedmo:
#                - versioned

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: dataTypeMeta
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            inversedBy: dataType
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
            fetch: EXTRA_LAZY
#            gedmo:
#                - versioned

    lifecycleCallbacks: {  }
