ODR\AdminBundle\Entity\DataTypeMeta:
    type: entity
    table: odr_data_type_meta
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        # Master Templates increment revision using this column.
        master_revision:
            type: integer
            unsigned: true
            nullable: false
            default: 0
        # This value tracks the current published revision of the master template.
        master_published_revision:
            type: integer
            unsigned: true
            nullable: false
            default: 0
            column: master_published_version
        # Databases created from master templates track the revision they are in compliance with here.
        tracking_master_revision:
            type: integer
            unsigned: true
            nullable: false
            default: 0

        searchSlug:
            type: string
            length: 32
            fixed: false
            nullable: true
            column: search_slug

        shortName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: short_name
        longName:
            type: string
            length: 128
            fixed: false
            nullable: false
            column: long_name
        description:
            type: text
            fixed: false
            nullable: true
            column: description
        xml_shortName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: xml_short_name

        useShortResults:
            type: boolean
            nullable: false
            default: true
            column: use_short_results

        publicDate:
            type: datetime
            nullable: false
            column: public_date

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        externalIdField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                external_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
        nameField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_name_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
        sortField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sort_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false
        backgroundImageField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                background_image_datafield_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: dataTypeMeta
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            inversedBy: dataType
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
            fetch: EXTRA_LAZY

    lifecycleCallbacks: {  }
