ODR\AdminBundle\Entity\DataTree:
    type: entity
    table: odr_data_tree
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        dataTreeMeta:
            targetEntity: DataTreeMeta
            cascade: { }
            mappedBy: dataTree
            inversedBy: null
            joinColumns:
                data_tree_meta_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToOne:
        ancestor:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ancestor_id:
                    referencedColumnName: id
            orphanRemoval: false
        descendant:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                descendant_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
