ODR\AdminBundle\Entity\DataTreeMeta:
    type: entity
    table: odr_data_tree_meta
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        is_link:
            type: boolean
            nullable: false
            default: false
            column: is_link
        multiple_allowed:
            type: boolean
            nullable: false
            default: true
            column: multiple_allowed

        edit_behavior:
            type: integer
            nullable: false
            default: 0
            column: edit_behavior

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        dataTree:
            targetEntity: DataTree
            cascade: {  }
            mappedBy: null
            inversedBy: dataTreeMeta
            joinColumns:
                data_tree_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
