ODR\AdminBundle\Entity\DataFields:
    type: entity
    table: odr_data_fields
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            mappedBy: dataField
            fetch: EXTRA_LAZY
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false

        themeDataFields:
            targetEntity: ThemeDataField
            cascade: {  }
            mappedBy: dataField
            orphanRemoval: false

        radioOptions:
            targetEntity: RadioOptions
            cascade: {  }
            mappedBy: dataField
            orphanRemoval: false

        dataFieldMeta:
            targetEntity: DataFieldsMeta
            cascade: { }
            mappedBy: dataField
            inversedBy: null
            joinColumns:
                data_field_meta_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToOne:
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: dataFields
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            inversedBy: dataFields
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
