ODR\AdminBundle\Entity\DataType:
    type: entity
    table: odr_data_type
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        revision:
            type: integer
            unsigned: true
            nullable: false
            default: 0
            column: revision

        has_shortresults:
            type: boolean
            nullable: false
            default: false
            column: has_shortresults
        has_textresults:
            type: boolean
            nullable: false
            default: false
            column: has_textresults

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            inversedBy: dataType
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
            fetch: EXTRA_LAZY

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    oneToMany:
        dataTypeMeta:
            targetEntity: DataTypeMeta
            cascade: { }
            mappedBy: dataType
            inversedBy: null
            joinColumns:
                data_type_meta_id:
                    referencedColumnName: id
            orphanRemoval: false

        themeDataType:
            targetEntity: ThemeDataType
            cascade: {  }
            mappedBy: dataType
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                theme_data_type_id:
                    referencedColumnName: id

        dataFields:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: dataType
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                data_fields_id:
                    referencedColumnName: id

        themes:
            targetEntity: Theme
            cascade: { }
            mappedBy: dataType
            inversedBy: null
            joinColumns:
                theme_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
