ODR\AdminBundle\Entity\DataRecord:
    type: entity
    table: odr_data_record
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    indexes:
        uuid_index:
            columns: [ unique_id ]

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        provisioned:
            type: boolean
            nullable: false
            default: true

        unique_id:
            type: string
            length: 32
            nullable: true
            default: ''
            column: unique_id

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:

        boolean:
            targetEntity: Boolean
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        integerValue:
            targetEntity: IntegerValue
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        decimalValue:
            targetEntity: DecimalValue
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        longText:
            targetEntity: LongText
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        longVarchar:
            targetEntity: LongVarchar
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        mediumVarchar:
            targetEntity: MediumVarchar
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        shortVarchar:
            targetEntity: ShortVarchar
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        datetimeValue:
            targetEntity: DatetimeValue
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        image:
            targetEntity: Image
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        file:
            targetEntity: File
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        radioSelection:
            targetEntity: RadioSelection
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        tagSelection:
            targetEntity: TagSelection
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: LAZY
            orphanRemoval: false

        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            mappedBy: dataRecord
            inversedBy: null
            fetch: EXTRA_LAZY
            orphanRemoval: false

        grandchildren:
            targetEntity: DataRecord
            mappedBy: grandparent
            fetch: EXTRA_LAZY
        children:
            targetEntity: DataRecord
            mappedBy: parent
            fetch: EXTRA_LAZY

        dataRecordMeta:
            targetEntity: DataRecordMeta
            cascade: { }
            mappedBy: dataRecord
            inversedBy: null
            orphanRemoval: false

        linkedDatarecords:
            targetEntity: LinkedDataTree
            cascade: { }
            mappedBy: ancestor
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        parent:
            targetEntity: DataRecord
            inversedBy: children
            fetch: EXTRA_LAZY

        grandparent:
            targetEntity: DataRecord
            fetch: EXTRA_LAZY
            inversedBy: grandchildren

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EXTRA_LAZY
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: dataRecords
            fetch: LAZY
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
