ODR\AdminBundle\Entity\FieldType:
    type: entity
    table: odr_field_type
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        typeClass:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: type_class
        typeName:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: type_name

        description:
            type: text
            nullable: true

        allowMultiple:
            type: boolean
            nullable: false
            column: allow_multiple

        insertOnCreate:
            type: boolean
            nullable: false
            column: insert_on_create
            default: 1

        canBeUnique:
            type: boolean
            nullable: false
            column: can_be_unique
            default: false
        canBeSortField:
            type: boolean
            nullable: false
            column: can_be_sort_field
            default: false

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
