ODR\AdminBundle\Entity\FileStorage:
    type: entity
    table: odr_file_storage
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        fileData:
            type: blob
            nullable: false
            column: file_data
            gedmo:
                - versioned
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        file:
            targetEntity: File
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                file_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
    lifecycleCallbacks: {  }
