ODR\AdminBundle\Entity\FileChecksum:
    type: entity
    table: odr_file_checksum
    gedmo:
#        soft_deleteable:
#            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        chunk_id:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        checksum:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: checksum

    manyToOne:
        file:
            targetEntity: File
            cascade: {  }
            mappedBy: null
            inversedBy: fileChecksum
            joinColumns:
                file_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
