ODR\AdminBundle\Entity\ImageChecksum:
    type: entity
    table: odr_image_checksum
    gedmo:
#        soft_deleteable:
#            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        chunk_id:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        checksum:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: checksum

    manyToOne:
        image:
            targetEntity: Image
            cascade: {  }
            mappedBy: null
            inversedBy: imageChecksum
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
