ODR\AdminBundle\Entity\ImageSizes:
    type: entity
    table: odr_image_sizes
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        width:
            type: integer
            unsigned: false
            nullable: false
            gedmo:
                - versioned
        height:
            type: integer
            unsigned: false
            nullable: false
            gedmo:
                - versioned
        minWidth:
            type: integer
            unsigned: false
            nullable: true
            column: min_width
            gedmo:
                - versioned
        minHeight:
            type: integer
            unsigned: false
            nullable: true
            column: min_height
            gedmo:
                - versioned
        maxWidth:
            type: integer
            unsigned: false
            nullable: true
            column: max_width
            gedmo:
                - versioned
        maxHeight:
            type: integer
            unsigned: false
            nullable: true
            column: max_height
            gedmo:
                - versioned
        size_constraint:
            type: string
            length: 24
            nullable: true
            column: size_constraint
            gedmo:
                - versioned
        original:
            type: boolean
            nullable: false
            gedmo:
                - versioned
        imagetype:
            type: string
            length: 24 
            nullable: true
            gedmo:
                - versioned
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        dataFields:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
#            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
