ODR\AdminBundle\Entity\ImageStorage:
    type: entity
    table: odr_image_storage
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        width:
            type: integer
            unsigned: false
            nullable: false
            gedmo:
                - versioned
        height:
            type: integer
            unsigned: false
            nullable: false
            gedmo:
                - versioned
        imageData:
            type: blob
            nullable: false
            column: image_data
            gedmo:
                - versioned
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
        image:
            targetEntity: Image
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
#            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
