ODR\AdminBundle\Entity\ImageSizes:
    type: entity
    table: odr_image_sizes
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        width:
            type: integer
            unsigned: false
            nullable: false
        height:
            type: integer
            unsigned: false
            nullable: false

        minWidth:
            type: integer
            unsigned: false
            nullable: true
            column: min_width
        minHeight:
            type: integer
            unsigned: false
            nullable: true
            column: min_height

        maxWidth:
            type: integer
            unsigned: false
            nullable: true
            column: max_width
        maxHeight:
            type: integer
            unsigned: false
            nullable: true
            column: max_height

        size_constraint:
            type: string
            length: 24
            nullable: true
            column: size_constraint

        original:
            type: boolean
            nullable: false

        imagetype:
            type: string
            length: 24 
            nullable: true

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        dataFields:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
