ODR\AdminBundle\Entity\ImageMeta:
    type: entity
    table: odr_image_meta
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        displayorder:
            type: integer
            column: display_order
            unsigned: false
#            gedmo:
#                - versioned

        caption:
            type: string
            length: 96
            fixed: false
            nullable: true
#            gedmo:
#                - versioned

        originalFileName:
            type: string
            length: 128
            fixed: false
            nullable: true
            column: original_file_name
#            gedmo:
#                - versioned

        external_id:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: external_id
#            gedmo:
#                - versioned

        publicDate:
            type: datetime
            nullable: false
            column: public_date
#            gedmo:
#                - versioned

        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        Image:
            targetEntity: Image
            cascade: {  }
            mappedBy: null
            inversedBy: ImageMeta
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }