ODR\AdminBundle\Entity\Image:
    type: entity
    table: odr_image
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    indexes:
        uuid_index:
            columns: [ unique_id ]
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        original:
            type: boolean
            nullable: false

        ext:
            type: string
            length: 8
            fixed: false
            nullable: true
            column: ext

        localFileName:
            type: string
            length: 128
            fixed: false
            nullable: true
            column: local_file_name

        encrypt_key:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: encrypt_key

        original_checksum:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: checksum

        imageWidth:
            type: integer
            column: image_width
            nullable: true
            unsigned: true

        imageHeight:
            type: integer
            column: image_height
            nullable: true
            unsigned: true

        unique_id:
            type: string
            length: 32
            nullable: true
            default: ''
            column: unique_id

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        children:
            targetEntity: Image
            mappedBy: parent

        imageChecksum:
            targetEntity: ImageChecksum
            cascade: { }
            mappedBy: image
            inversedBy: null
            orphanRemoval: false

        imageMeta:
            targetEntity: ImageMeta
            cascade: { }
            mappedBy: image
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        parent:
            targetEntity: Image
            inversedBy: children

        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecord:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_record_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            mappedBy: null
            inversedBy: image
            joinColumns:
                data_record_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        imageSize:
            targetEntity: ImageSizes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_size_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: 
        prePersist: [ preUpload ]
        postPersist: [ upload ]
        preUpdate: [ preUpload ]
        postUpdate: [ upload ]
        preRemove: [ storeFilenameForRemove ]
        postRemove: [ removeUpload ]
