ODR\AdminBundle\Entity\LinkedDataTree:
    type: entity
    table: odr_linked_data_tree
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

#    oneToMany:
#        ldtAncestors:
#            targetEntity: linkedDataTree
#            mappedBy: descendant
#
#    manyToOne:
#        ldtDescendants:
#            targetEntity: linkedDataTree
#            inversedBy: ancestor

    manyToOne:
        ancestor:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: linkedDatarecords
            joinColumns:
                ancestor_id:
                    referencedColumnName: id
            orphanRemoval: false
        descendant:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                descendant_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
