ODR\AdminBundle\Entity\LongVarchar:
    type: entity
    table: odr_long_varchar
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: string
            length: 255
            fixed: false
            nullable: false
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
        dataRecord:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_record_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            inversedBy: longVarchar
            joinColumns:
                data_record_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
