ODR\AdminBundle\Entity\RadioOptions:
    type: entity
    table: odr_radio_options
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    indexes:
        uuid_index:
            columns: [ radio_option_uuid ]

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        # This property MUST exist and be kept up to date, otherwise CSV/XML importing are unable to concurrently check whether a RadioOption exists
        optionName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: option_name

        # Option Unique ID is the related option id from the master template if the field template
        # derived.  If not template derived, the radio option is custom made and has it's own unique
        # id.
        radioOptionUuid:
            type: string
            length: 32
            nullable: true
            default: ''
            column: radio_option_uuid

        userCreated:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        radioOptionMeta:
            targetEntity: RadioOptionsMeta
            cascade: {  }
            mappedBy: radioOption
            inversedBy: null
            orphanRemoval: false

        radioSelections:
            targetEntity: RadioSelection
            cascade: {  }
            mappedBy: radioOption
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            inversedBy: radioOptions
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
