ODR\AdminBundle\Entity\RadioSelection:
    type: entity
    table: odr_radio_selection
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        selected:
            type: integer
            unsigned: false
            nullable: false
            default: 0
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    manyToOne:
        radioOption:
            targetEntity: RadioOptions
            cascade: {  }
            mappedBy: null
            inversedBy: radioSelections
            joinColumns:
                radio_option_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

#    oneToOne:
        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
            inversedBy: radioSelection
            joinColumns:
                data_record_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
    lifecycleCallbacks: {  }
