ODR\AdminBundle\Entity\RadioOptions:
    type: entity
    table: odr_radio_options
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        # This property MUST exist and be kept up to date, otherwise CSV/XML importing are unable to concurrently check whether a RadioOption exists
        optionName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: option_name

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        radioOptionMeta:
            targetEntity: RadioOptionsMeta
            cascade: {  }
            mappedBy: radioOption
            inversedBy: null
            joinColumns:
                radio_meta_id:
                    referencedColumnName: id

        radioSelections:
            targetEntity: RadioSelection
            cascade: {  }
            mappedBy: radioOption
            inversedBy: null
            joinColumns:
                radio_selection_id:
                    referencedColumnName: id

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            inversedBy: radioOptions
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
