ODR\AdminBundle\Entity\RadioOptions:
    type: entity
    table: odr_radio_options
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        # This property MUST exist and be kept up to date, otherwise CSV/XML importing are unable to concurrently check whether a RadioOption exists
        optionName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: option_name
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

        # TODO - delete these four properties
        xml_optionName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: xml_option_name
#            gedmo:
#                - versioned
        displayOrder:
            type: integer
            unsigned: false
            nullable: false
            column: display_order
#            gedmo:
#                - versioned
        isDefault:
            type: boolean
            nullable: false
            default: false
            column: is_default
#            gedmo:
#                - versioned
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    oneToMany:
        radioOptionsMeta:
            targetEntity: RadioOptionsMeta
            cascade: {  }
            mappedBy: radioOptions
            inversedBy: null
            joinColumns:
                radio_meta_id:
                    referencedColumnName: id
#            gedmo:
#                - versioned

    manyToOne:
        dataFields:
            targetEntity: DataFields
            cascade: {  }
            inversedBy: radioOptions
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

        # TODO - delete this property
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
#            gedmo:
#                blameable:
#                    on: update

    lifecycleCallbacks: {  }
