ODR\AdminBundle\Entity\RadioOptionsMeta:
    type: entity
    table: odr_radio_options_meta
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        optionName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: option_name
#            gedmo:
#                - versioned
        xml_optionName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: xml_option_name
#            gedmo:
#                - versioned
        displayOrder:
            type: integer
            unsigned: false
            nullable: false
            column: display_order
#            gedmo:
#                - versioned
        isDefault:
            type: boolean
            nullable: false
            default: false
            column: is_default
#            gedmo:
#                - versioned

        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        radioOptions:
            targetEntity: RadioOptions
            cascade: {  }
            mappedBy: null
            inversedBy: radioOptionsMeta
            joinColumns:
                radio_option_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }