ODR\AdminBundle\Entity\RenderPluginFields:
    type: entity
    table: odr_render_plugin_fields
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        allowedFieldtypes:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: allowed_fieldtypes
            gedmo:
                - versioned

        fieldName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: field_name
            gedmo:
                - versioned
        description:
            type: text
            fixed: false
            nullable: true
            column: description
            gedmo:
                - versioned
        active:
            type: boolean
            nullable: false
            column: active
            gedmo:
                - versioned
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:

        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginFields
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned

#        fieldType:
#            targetEntity: FieldType
#            cascade: {  }
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                field_type_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
