ODR\AdminBundle\Entity\RenderPluginInstance:
    type: entity
    table: odr_render_plugin_instance
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        active:
            type: boolean
            nullable: false
            column: active

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        renderPluginOptions:    # TODO - get rid of this
            targetEntity: RenderPluginOptions
            cascade: {  }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginMap:
            targetEntity: RenderPluginMap
            cascade: {  }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginOptionsMap:
            targetEntity: RenderPluginOptionsMap
            cascade: {  }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        themeRenderPluginInstance:
            targetEntity: ThemeRenderPluginInstance
            cascade: { }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginThemeOptionsMap:
            targetEntity: RenderPluginThemeOptionsMap
            cascade: { }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

    manyToOne:
        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginInstance
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: dataType
            inversedBy: renderPluginInstances
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: dataFields
            inversedBy: renderPluginInstances
            fetch: LAZY
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
