ODR\AdminBundle\Entity\RenderPluginMap:
    type: entity
    table: odr_render_plugin_map
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    manyToOne:
        renderPluginFields:
            targetEntity: RenderPluginFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                render_plugin_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned

        renderPluginInstance:
            targetEntity: RenderPluginInstance
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginMap
            joinColumns:
                render_plugin_instance_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy:  null
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
