ODR\AdminBundle\Entity\RenderPluginInstance:
    type: entity
    table: odr_render_plugin_instance
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        active:
            type: boolean
            nullable: false
            column: active
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    oneToMany:
        renderPluginOptions:
            targetEntity: RenderPluginOptions
            cascade: {  }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginMap:
            targetEntity: RenderPluginMap
            cascade: {  }
            mappedBy: renderPluginInstance
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

    manyToOne:
        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginInstance
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy:  null
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: update

    lifecycleCallbacks: {  }
