ODR\AdminBundle\Entity\RenderPlugin:
    type: entity
    table: odr_render_plugin
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        pluginName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: plugin_name
        description:
            type: text
            fixed: false
            nullable: true
            column: description

        category:
            type: string
            length: 32
            fixed: false
            nullable: false

        pluginClassName:
            type: string
            length: 128 
            fixed: false
            nullable: false
            column: plugin_class_name

        active:
            type: boolean
            nullable: false
            column: active
        render:
            type: boolean
            nullable: false
            column: render

        overrideChild:
            type: boolean
            nullable: false
            column: override_child
            default: false
        overrideFields:
            type: boolean
            nullable: false
            column: override_fields
            default: false
        overrideFieldReload:
            type: boolean
            nullable: false
            column: override_field_reload
            default: false

        plugin_type:
            type: smallint
            default: 2
            unsigned: false
            nullable: false
            column: plugin_type

        deletedAt:
            type: datetime
            nullable: true
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    indexes:
        rp_classname:
            columns: ["plugin_class_name"]

    oneToMany:
        renderPluginInstance:
            targetEntity: RenderPluginInstance
            cascade: {  }
            mappedBy: renderPlugin
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginFields:
            targetEntity: RenderPluginFields
            cascade: {  }
            mappedBy: renderPlugin
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginEvents:
            targetEntity: RenderPluginEvents
            cascade: {  }
            mappedBy: renderPlugin
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

        renderPluginOptionsDef:
            targetEntity: RenderPluginOptionsDef    # TODO - change to RenderPluginOptions
            cascade: { }
            mappedBy: renderPlugin
            inversedBy: null
#            fetch: LAZY
            orphanRemoval: false

    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
