ODR\AdminBundle\Entity\RenderPluginFields:
    type: entity
    table: odr_render_plugin_fields
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        allowedFieldtypes:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: allowed_fieldtypes

        fieldName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: field_name
        description:
            type: text
            fixed: false
            nullable: true
            column: description

        active:
            type: boolean
            nullable: false
            column: active

        must_be_unique:
            type: boolean
            nullable: false
            default: false
            column: must_be_unique
        single_uploads_only:
            type: boolean
            nullable: false
            default: false
            column: single_uploads_only
        no_user_edits:
            type: boolean
            nullable: false
            default: false
            column: no_user_edits
        autogenerate_values:
            type: boolean
            nullable: false
            default: false
            column: autogenerate_values
        is_derived:
            type: boolean
            nullable: false
            default: false
            column: is_derived
        is_optional:
            type: boolean
            nullable: false
            default: false
            column: is_optional

        deletedAt:
            type: datetime
            nullable: true
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

    indexes:
        rpf_name:
            columns: ["field_name"]

        unique_idx:
            columns: ["must_be_unique"]
        uploads_idx:
            columns: ["single_uploads_only"]
        edits_idx:
            columns: ["no_user_edits"]
        autogenerate_idx:
            columns: ["autogenerate_values"]
        derived_idx:
            columns: ["is_derived"]

    manyToOne:
        renderPlugin:
            targetEntity: RenderPlugin
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginFields
            joinColumns:
                render_plugin_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
