ODR\AdminBundle\Entity\RenderPluginOptions:
    type: entity
    table: odr_render_plugin_options
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        optionName:
            type: string
            length: 32
            fixed: false
            nullable: false
            column: option_name
            gedmo:
                - versioned
        optionValue:
            type: text
            fixed: false
            nullable: true
            column: option_value
            gedmo:
                - versioned
        active:
            type: boolean
            nullable: false
            column: active
            gedmo:
                - versioned
        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        renderPluginInstance:
            targetEntity: RenderPluginInstance
            cascade: {  }
            mappedBy: null
            inversedBy: renderPluginOptions
            joinColumns:
                render_plugin_instance_id:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
