ODR\AdminBundle\Entity\ShortVarchar:
    type: entity
    table: odr_short_varchar
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: string
            length: 32
            fixed: false
            nullable: false

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    indexes:
        shortvarchar_created:
            columns: ["created"]
        shortvarchar_fulltext:
            columns: ["value"]
            flags: fulltext

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false

        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecord:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: shortVarchar
            joinColumns:
                data_record_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
#            mappedBy: null
            inversedBy: shortVarchar
            joinColumns:
                data_record_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
