ODR\AdminBundle\Entity\SidebarLayoutMap:
    type: entity
    table: odr_sidebar_layout_map
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        category:
            type: integer
            nullable: false
            column: category

        displayOrder:
            type: integer
            nullable: false
            column: display_order

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        sidebarLayout:
            targetEntity: SidebarLayout
            cascade: {  }
            mappedBy: null
            inversedBy: sidebarLayoutMap
            joinColumns:
                sidebar_layout_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy:  null
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                data_field_id:
                    referencedColumnName: id
                    nullable: true
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
