ODR\AdminBundle\Entity\TagMeta:
    type: entity
    table: odr_tag_meta
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        tagName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: tag_name
        xml_tagName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: xml_tag_name

        displayOrder:
            type: integer
            unsigned: false
            nullable: false
            column: display_order

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        tag:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: tagMeta
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
