ODR\AdminBundle\Entity\Tags:
    type: entity
    table: odr_tags
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    indexes:
        uuid_index:
            columns: [ tag_uuid ]

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        # This property MUST exist and be kept up to date, otherwise CSV/XML importing are unable
        #  to concurrently check whether a RadioOption exists
        tagName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: tag_name

        # Option Unique ID is the related option id from the master template if the field template
        # derived.  If not template derived, the tag is custom made and has it's own unique id.
        tagUuid:
            type: string
            length: 32
            nullable: true
            default: ''
            column: tag_uuid

        userCreated:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        tagMeta:
            targetEntity: TagMeta
            cascade: {  }
            mappedBy: tag
            inversedBy: null
            orphanRemoval: false

        tagSelections:
            targetEntity: TagSelection
            cascade: {  }
            mappedBy: tag
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            inversedBy: tags
            joinColumns:
                data_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
