ODR\AdminBundle\Entity\TagTree:
    type: entity
    table: odr_tag_tree
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        parent:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false

        child:
            targetEntity: Tags
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                child_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
