ODR\AdminBundle\Entity\ThemeElement:
    type: entity
    table: odr_theme_element
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        themeDataFields:
            targetEntity: ThemeDataField
            cascade: [ "persist" ]
            mappedBy: themeElement
            inversedBy: null
            orphanRemoval: false

        themeDataType:
            targetEntity: ThemeDataType
            cascade: [ "persist" ]
            mappedBy: themeElement
            inversedBy: null
            orphanRemoval: false

        themeRenderPluginInstance:
            targetEntity: ThemeRenderPluginInstance
            cascade: [ "persist" ]
            mappedBy: themeElement
            inversedBy: null
            orphanRemoval: false

        themeElementMeta:
            targetEntity: ThemeElementMeta
            cascade: [ "persist" ]
            mappedBy: themeElement
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: themeElements
            joinColumns:
                theme_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
