ODR\AdminBundle\Entity\ThemeDataField:
    type: entity
    table: odr_theme_data_field
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

#        templateType:
#            type: string
#            length: 45
#            fixed: false
#            nullable: false
#            column: template_type
#            gedmo:
#                - versioned
#        css:
#            type: text
#            nullable: true
#            gedmo:
#                - versioned

        displayOrder:
            type: integer
            nullable: false
            column: display_order
#            gedmo:
#                - versioned

        cssWidthMed:
            type: string
            length: 32
#            gedmo:
#                - versioned
        cssWidthXL:
            type: string
            length: 32
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned


        #TODO - delete the following property
        active:
            type: boolean
            nullable: false
            default: true
            column: active
#            gedmo:
#                - versioned

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: themeDataFields
            joinColumns:
                data_field_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        themeElement:
            targetEntity: ThemeElement
            cascade: {  }
            mappedBy: null
            inversedBy: themeDataFields
            joinColumns:
                theme_element_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#               - versioned
#            gedmo:
#                blameable:
#                    on: update
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

        #TODO - delete the following property
        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                theme_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

    lifecycleCallbacks: {  }
