ODR\AdminBundle\Entity\ThemeMeta:
    type: entity
    table: odr_theme_meta
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        templateName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: template_name
#            gedmo:
#                - versioned
        templateDescription:
            type: text
            nullable: true
            column: template_description
#            gedmo:
#                - versioned
        isDefault:
            type: boolean
            nullable: false
            column: is_default
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned

    manyToOne:
        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: themeMeta
            joinColumns:
                theme_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }
