ODR\AdminBundle\Entity\ThemeMeta:
    type: entity
    table: odr_theme_meta
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        templateName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: template_name

        templateDescription:
            type: text
            nullable: true
            column: template_description

        defaultFor:
            type: integer
            unsigned: false
            nullable: false
            default: 0
            column: default_for

        displayOrder:
            type: integer
            unsigned: false
            nullable: true
            column: display_order

        shared:
            type: boolean
            nullable: false
            default: false

        sourceSyncVersion:
            type: integer
            unsigned: true
            nullable: true
            column: source_sync_version

        disableSearchSidebar:
            type: boolean
            nullable: false
            default: false
            column: disable_search_sidebar

        themeVisibility:
            type: integer
            nullable: false
            default: 0

        isTableTheme:
            type: boolean
            nullable: false
            default: false

        # these options are specific to table themes
        displaysAllResults:
            type: boolean
            nullable: false
            default: false
        enableHorizontalScrolling:
            type: boolean
            nullable: false
            default: false
            column: enable_horizontal_scrolling

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        theme:
            targetEntity: Theme
            cascade: ["persist"]
            mappedBy: null
            inversedBy: themeMeta
            joinColumns:
                theme_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
