ODR\AdminBundle\Entity\Theme:
    type: entity
    table: odr_theme
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

#        templateName:
#            type: string
#            length: 64
#            fixed: false
#            nullable: false
#            column: template_name
#            gedmo:
#                - versioned
#        templateDescription:
#            type: text
#            nullable: true
#            column: template_description
#            gedmo:
#                - versioned
#        templateType:
#            type: string
#            length: 32
#            default: 'form'
#            column: template_type
#            gedmo:
#                - versioned
#        templatePreview:
#            type: blob
#            nullable: true
#            column: template_preview
#            gedmo:
#                - versioned
#        isDefault:
#            type: boolean
#            nullable: false
#            column: is_default
#            gedmo:
#                - versioned

        themeType:
            type: text
            length: 32
            nullable: false
            column: theme_type
#            gedmo:
#                - versioned

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
#            gedmo:
#                - versioned



    oneToMany:
        themeMeta:
            targetEntity: ThemeMeta
            cascade: { }
            mappedBy: theme
            inversedBy: null
            joinColumns:
                theme_meta_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        themeElements:
            targetEntity: ThemeElement
            cascade: { }
            mappedBy: theme
            inversedBy: null
            joinColumns:
                theme_element_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

    manyToOne:
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: themes
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                - versioned

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: update
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }
