ODR\AdminBundle\Entity\Theme:
    type: entity
    table: odr_theme
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        themeType:
            type: text
            length: 32
            nullable: false
            column: theme_type

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        themeMeta:
            targetEntity: ThemeMeta
            cascade: { }
            mappedBy: theme
            inversedBy: null
            joinColumns:
                theme_meta_id:
                    referencedColumnName: id
            orphanRemoval: false

        themeElements:
            targetEntity: ThemeElement
            cascade: { }
            mappedBy: theme
            inversedBy: null
            joinColumns:
                theme_element_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToOne:
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: themes
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
