ODR\AdminBundle\Entity\ThemePreferences:
    type: entity
    table: odr_theme_preferences
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        isDefault:
            type: boolean
            nullable: false
            column: is_default

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: themePreferences
            joinColumns:
                theme_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: relatedDatatypes
            joinColumns:
                datatype_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
