ODR\AdminBundle\Entity\ThemeDataType:
    type: entity
    table: odr_theme_data_type
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        display_type:
            type: integer
            nullable: false
            default: 0
            column: display_type

        hidden:
            type: integer
            nullable: false
            default: 0

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        # intentionally not defining mappedBy/inversedBy...don't want the Theme entity to have
        #  properties/functions referring back to here
        childTheme:
            targetEntity: Theme
            cascade: {  }
            joinColumns:
                child_theme_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false

        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: themeDataType
            joinColumns:
                data_type_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false

        themeElement:
            targetEntity: ThemeElement
            cascade: {  }
            mappedBy: null
            inversedBy: themeDataType
            joinColumns:
                theme_element_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
