ODR\AdminBundle\Entity\ThemeRenderPluginInstance:
    type: entity
    table: odr_theme_render_plugin_instance
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        renderPluginInstance:
            targetEntity: RenderPluginInstance
            cascade: {  }
            mappedBy: null
            inversedBy: themeRenderPluginInstance
            joinColumns:
                render_plugin_instance_id:
                    referencedColumnName: id
            orphanRemoval: false

        themeElement:
            targetEntity: ThemeElement
            cascade: {  }
            mappedBy: null
            inversedBy: themeRenderPluginInstance
            joinColumns:
                theme_element_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
