ODR\AdminBundle\Entity\ThemeElement:
    type: entity
    table: odr_theme_element
    gedmo:
        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        templateType:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: template_type
            gedmo:
                - versioned
        elementType:
            type: string
            length: 45
            fixed: false
            nullable: false
            column: element_type
            gedmo:
                - versioned
#        xpos:
#            type: integer
#            unsigned: false
#            nullable: false
#            gedmo:
#                - versioned
#        ypos:
#            type: integer
#            unsigned: false
#            nullable: false
#            gedmo:
#                - versioned
#        zpos:
#            type: integer
#            unsigned: false
#            nullable: false
#            gedmo:
#                - versioned
#        width:
#            type: integer
#            unsigned: false
#            nullable: false
#            gedmo:
#                - versioned
#        height:
#            type: integer
#            unsigned: false
#            nullable: false
#            gedmo:
#                - versioned
        css:
            type: text
            nullable: true
            gedmo:
                - versioned
#        fieldWidth:
#            type: integer
#            nullable: false
#            column: field_width
#            gedmo:
#                - versioned
#        fieldHeight:
#            type: integer
#            nullable: false
#            column: field_height
#            gedmo:
#                - versioned
        displayOrder:
            type: integer
            nullable: false
            column: display_order
            gedmo:
                - versioned
        displayInResults:
            type: boolean
            nullable: false
            default: true
            column: display_in_results
            gedmo:
                - versioned

        cssWidthXL:
            type: string
            length: 32
            gedmo:
                - versioned
        cssWidthMed:
            type: string
            length: 32
            gedmo:
                - versioned

        deletedAt:
            type: date
            nullable: true
            gedmo:
                - versioned
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        themeElementField:
            targetEntity: ThemeElementField
            cascade: {  }
            mappedBy: themeElement
            inversedBy: null
            fetch: LAZY
            joinColumns:
                theme_data_type_id:
                    referencedColumnName: id
            orderBy:
                displayOrder: ASC
                id: ASC
            gedmo:
                - versioned
    manyToOne:
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: themeElement
            joinColumns:
                data_type_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                theme_id:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                - versioned
#            gedmo:
#                blameable:
#                    on: update
    lifecycleCallbacks: {  }
