ODR\AdminBundle\Entity\TrackedError:
    type: entity
    table: odr_tracked_error
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        error_level:
            type: string
            length: 32
            nullable: false
            fixed: false
        error_category:
            type: string
            length: 64
            nullable: false
            fixed: false
        error_body:
            type: text
            nullable: false

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        trackedJob:
            targetEntity: TrackedJob
            cascade: {  }
            mappedBy: null
            inversedBy: trackedError
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
