ODR\AdminBundle\Entity\TrackedCSVExport:
    type: entity
    table: odr_tracked_csv_export
#    gedmo:
#        soft_deleteable:
#            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        random_key:
            type: string
            length: 32
            fixed: false
            nullable: false

        finalize:
            type: boolean
            nullable: false
            default: false

        job_order:
            type: integer
            unsigned: false
            nullable: true

    manyToOne:
        trackedJob:
            targetEntity: TrackedJob
            cascade: {  }
            mappedBy: null
            inversedBy: trackedCSVExport
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
