# ----------------------------------------
# IMPORTANT: CSVExportHelperService inserts directly into this table, bypassing doctrine
# Changes here need to be manually added over there too
# ----------------------------------------
ODR\AdminBundle\Entity\TrackedCSVExport:
    type: entity
    table: odr_tracked_csv_export
#    gedmo:
#        soft_deleteable:
#            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        random_key:
            type: string
            length: 32
            fixed: false
            nullable: false

        job_order:
            type: integer
            unsigned: false
            nullable: true

        line_count:
            type: integer
            unsigned: false
            nullable: true

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    manyToOne:
        trackedJob:
            targetEntity: TrackedJob
            cascade: {  }
            mappedBy: null
            inversedBy: trackedCSVExport
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
