ODR\AdminBundle\Entity\TrackedJob:
    type: entity
    table: odr_tracked_job
    gedmo:
#        loggable: true
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        job_type:
            type: string
            length: 64
            fixed: false
            nullable: false

        target_entity:
            type: string
            length: 64
            fixed: false
            nullable: false

        additional_data:
            type: text
            nullable: false

        restrictions:
            type: string
            length: 255
            fixed: false
            nullable: true

        current:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        total:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        completed:
            type: datetime
            default: null
            nullable: true

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

        started:
            type: datetime
            default: null
            nullable: true

        deletedAt:
            type: date
            nullable: true
#            gedmo:
#                - versioned

    oneToMany:
        trackedCSVExport:
            targetEntity: TrackedCSVExport
            cascade: {  }
            mappedBy: trackedJob
            inversedBy: null
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id
#            gedmo:
#                - versioned

        trackedError:
            targetEntity: TrackedError
            cascade: {  }
            mappedBy: trackedJob
            inversedBy: null
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id
#            gedmo:
#                - versioned

    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
#            gedmo:
#                blameable:
#                    on: create

    lifecycleCallbacks: {  }
