ODR\AdminBundle\Entity\TrackedJob:
    type: entity
    table: odr_tracked_job
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        job_type:
            type: string
            length: 64
            fixed: false
            nullable: false

        target_entity:
            type: string
            length: 64
            fixed: false
            nullable: false

        additional_data:
            type: text
            nullable: false

        restrictions:
            type: string
            length: 255
            fixed: false
            nullable: true

        current:
            type: integer
            unsigned: false
            nullable: false
            default: 0
        total:
            type: integer
            unsigned: false
            nullable: false
            default: 0

        started:
            type: datetime
            default: null
            nullable: true
        completed:
            type: datetime
            default: null
            nullable: true

        failed:
            type: boolean
            default: false
        viewed:
            type: datetime
            default: null
            nullable: true

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        trackedCSVExport:
            targetEntity: TrackedCSVExport
            cascade: {  }
            mappedBy: trackedJob
            inversedBy: null
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id

        trackedError:
            targetEntity: TrackedError
            cascade: {  }
            mappedBy: trackedJob
            inversedBy: null
            joinColumns:
                tracked_job_id:
                    referencedColumnName: id

    manyToOne:
        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
