ODR\AdminBundle\Entity\XYZData:
    type: entity
    table: odr_xyz_data
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    indexes:
        XYZData_created:
            columns: [ "created" ]
        x_value_index:
            columns: [ "x_value" ]
        y_value_index:
            columns: [ "y_value" ]
        z_value_index:
            columns: [ "z_value" ]

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        x_value:
            type: float
            unsigned: false
            nullable: true
            default: 0
        y_value:
            type: float
            unsigned: false
            nullable: true
            default: 0
        z_value:
            type: float
            unsigned: false
            nullable: true
            default: 0

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        dataField:
            targetEntity: DataFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_field_id:
                    referencedColumnName: id
            orphanRemoval: false

        fieldType:
            targetEntity: FieldType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                field_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecord:
            targetEntity: DataRecord
            cascade: {  }
            mappedBy: null
            inversedBy: XYZData
            joinColumns:
                data_record_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataRecordFields:
            targetEntity: DataRecordFields
            cascade: {  }
#            mappedBy: null
            inversedBy: XYZData
            joinColumns:
                data_record_fields_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
